### PR TITLE
Fix Parameter ModelCodes not reacting in ED Tree after update of the …

### LINKED ISSUE #1014: Parameter ModelCodes not reacting in ED Tree after update of the ED
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When the shortname of an ED is edited, the model code of the underlying parameter rows in the ED tree is not automatically updated.

Check in ElementDefinition browser and Product Tree.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

### PR DESCRIPTION
**Pull request by omaratrhea**
…ED; fixes #1014

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix Parameter ModelCodes not reacting in ED Tree and product tree after update of the ED

### CODE REVIEW

File: EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ParameterBaseRowViewModel.cs [hunk 1]
```diff
@@ -344,6 +344,19 @@ protected override void UpdateThingStatus()
             this.ThingStatus = new ThingStatus(this.Thing);
         }
 
+        /// <summary>
+        /// Update the model code property of itself and all contained rows recursively
+        /// </summary>
+        public void UpdateModelCode()
+        {
+            this.ModelCode = this.Thing.ModelCode();
+            foreach (var containedRow in this.ContainedRows)
```
Comment (lxatrhea) [inline EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ParameterBaseRowViewModel.cs:353]: Maybe an idea to create a method  at IRowViewModelBase level that handles the repeating code? Then we cannot forget this and in the rare case that there is an IRowViewModel in the visual tree that doesn't implement IHaveModelCode the traversal chain is not broken.

**Review by lxatrhea — CHANGES_REQUESTED** [review]
Possible broken traversal chain and repeating code.

File: EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ParameterBaseRowViewModel.cs (hunk 1 above)
Comment (omaratrhea) [reply EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ParameterBaseRowViewModel.cs:353]: I discussed with Alex, and there are enough differences now between Element definition and product tree implementations and different row types that doesn't make sense to abstract to higher level. He said not to do it for now.

**Review by alexatrhea — APPROVED** [review]
