### PR TITLE
GH1021-Initial implementation of MessageBusHandler;Fixes #1021

### LINKED ISSUE #1021: Excessive loading time and memory usage for Element Definitions View on large models
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the COMET-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Loading of models with a large number of element definitions and parameters (at present, circa 200 EDs containing ~5-20 Parameters per ED => on the order of 1000-2000 elements) causes full application lockup for more than 10 minutes, and in general results in unusable performance issues with the (latest) COMET IME client. 

The issue does not occur on initial loading of model and iteration. Upon opening the "Element Definitions" view, the loading freezes the application (appearing as a "Not Responding" state to the Task Manager), and the application memory usage balloons to an excessive level (in the range of 5-10 GB).

There are similar lockup issues when closing the Model/Iteration after loading the view. We observed a greater than 20 minute waiting period to close the iteration (with application freezing). Once the iteration is closed, the application keeps an excessive RAM usage (from 300 MB on fresh instance to 5.8GB afterwards) with no other models/iterations loaded. This smells like a memory leak on the client.

I noticed ticket #765 which discusses optimisations in the same direction as this problem, but at our scale the application performance is unusable at present.

This issue does not seem to be related to the performance of the web services, as the serialised data is returned efficiently (on the order of seconds for the whole iteration). The same issue occurs when loading from a JSON file.

#### Machine 1

**Element Definitions View - Opening time**
sn-ed-load-time

**Memory Consumption**
sn-memory-consumption

#### Machine 2

**Element Definitions View - Opening time**
jw-ed-load-time

**Memory Consumption - With ED View / Iteration Open**
jw-memory-consumption-opening

**Memory Consumption - With All Models/Iterations Closed**
jw-memory-consumption-closed

### Steps to Reproduce
- Load large model with many ElementDefinitions / Parameters (example model can be sent via email)
- Open Element Definitions View

### Logs

  - [X] There are no logs regarding the issue (no logs that I'm aware of but can provide if needed)
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [X] COMET-IME: 9.0.1.1
  - [ ] Other: 
  -
- Web Services:
  - [X] CDP4/COMET Web Services version: 4.0.0 (WSP) / 1.3.0 (DB)
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): Win 10 64-bit
  - [ ] Additional information:

### PR DESCRIPTION
**Pull request by lxatrhea**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
ElementDefinitionBrowser MessageBusHandler implementation

### CODE REVIEW

File: CDP4Composition/Mvvm/RowViewModelBase.cs [hunk 1]
```diff
@@ -340,30 +362,77 @@ public virtual bool IsEditable(string propertyName = "")
...
+                this.Disposables.Add(highlightSubscription);
+
+                // category highlighting
+                if (this.Thing is ICategorizableThing thingAsCategorizableThing)
                 {
-                    var highlightCategorySubscription = CDPMessageBus.Current.Listen<HighlightByCategoryEvent>(category)
-                        .ObserveOn(RxApp.MainThreadScheduler)
-                        .Subscribe(_ => this.HighlightEventHandler());
-                    this.Disposables.Add(highlightCategorySubscription);
+                    // TODO: if this is indeed a categorizable thing we also have to listen to changes on added/removed categories. Need to figure out how to do this best
```
Comment (samatrhea) [inline CDP4Composition/Mvvm/RowViewModelBase.cs:376]: can you add a GH ticket and put that number here please?

File: CDP4Composition/Mvvm/ViewModelBase.cs [hunk 2]
```diff
@@ -81,7 +98,7 @@ public abstract class ViewModelBase<T> : ReactiveObject, IViewModelBase<T>, IISe
         /// </summary>
         protected ViewModelBase()
         {
-            logger = LogManager.GetLogger(this.GetType().FullName);
+            InitializeLogger();
```
Comment (samatrhea) [inline CDP4Composition/Mvvm/ViewModelBase.cs:101]: missing `this.`

File: CDP4Composition/Mvvm/ViewModelBase.cs [hunk 3]
```diff
@@ -95,22 +112,111 @@ protected ViewModelBase()
...
+        {
+            logger = LogManager.GetLogger(this.GetType().FullName);
+        }
+
+        /// <summary>
+        /// Execute code that needs te run before all code in the hierarchy of constructors is executed, but after a ContainerViewModel was added
+        /// </summary>
+        protected virtual void BeforeInitialize()
+        {
+            var searchContainerViewModel = this.ContainerViewModel;
```
Comment (samatrhea) [inline CDP4Composition/Mvvm/ViewModelBase.cs:198]: not clear to me why this is called `searchContainerViewModel`, what is the relationship with search?

File: EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ElementBaseRowViewModel.cs [hunk 4]
```diff
@@ -298,17 +300,29 @@ protected override void InitializeSubscriptions()
...
-            var ownerListener = CDPMessageBus.Current.Listen<ObjectChangedEvent>(this.Thing.Owner)
-                .Where(objectChange => objectChange.EventKind == EventKind.Updated)
-                .ObserveOn(RxApp.MainThreadScheduler)
-                .Subscribe(
-                    x =>
+            Func<ObjectChangedEvent, bool> discriminator = objectChange => objectChange.EventKind == EventKind.Updated;
+            Action<ObjectChangedEvent> action = 
+                x =>
                     {
                         this.OwnerName = this.Thing.Owner.Name;
```
Comment (samatrhea) [inline EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ElementBaseRowViewModel.cs:307]: can you call `this.UpdateOwnerProperties()` here?

File: EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ParameterValueBaseRowViewModel.cs [hunk 5]
```diff
@@ -524,11 +536,25 @@ private void AddValueSetListener(ParameterValueSetBase thing)
...
 
-            var listener = CDPMessageBus.Current.Listen<ObjectChangedEvent>(thing)
-                            .Where(objectChange => objectChange.EventKind == EventKind.Updated && objectChange.ChangedThing.RevisionNumber > this.RevisionNumber)
-                            .ObserveOn(RxApp.MainThreadScheduler)
-                            .Subscribe(_ => this.SetValues());
-            this.Disposables.Add(listener);
+            Func<ObjectChangedEvent, bool> discriminator = objectChange => objectChange.EventKind == EventKind.Updated && objectChange.ChangedThing.RevisionNumber > this.RevisionNumber;
+            Action<ObjectChangedEvent> action = x => this.SetValues();
+
+            if (this.AllowMessageBusSubscriptions)
```
Comment (samatrhea) [inline EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ParameterValueBaseRowViewModel.cs:542]: will this code ever execute? i doubt it will since you've refactored the whole ElementDef browser and this class is only used there... if that is the case, should we not remove?

**Review by samatrhea — APPROVED** [review]

**Review by alexatrhea — APPROVED** [review]

File: CDP4Composition/Mvvm/ViewModelBase.cs (hunk 3 above)
Comment (lxatrhea) [reply CDP4Composition/Mvvm/ViewModelBase.cs:198]: Idea was to search up the ViewModel tree hierarchy for an object that implements IHaveMessageBusHandler, so that could be used by the child RowViewModels. That's the reason the the term "search" was added. But if it confuses it more, that's not good, so I removed it.

File: EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ParameterValueBaseRowViewModel.cs (hunk 5 above)
Comment (lxatrhea) [reply EngineeringModel/ViewModels/ElementDefinitionBrowser/ElementDefinitionTreeRows/ParameterValueBaseRowViewModel.cs:542]: I think that is the same as for others. 
I initially chose to do it like this, so no other code (unexpected usages of ElementDefinitionTree RowViewModels) will fail. 
I had some unexpected failing unit tests before I created the automatic setting of the AllowMessageBusSubscriptions property in ViewModelBase. Before, I set the AllowMessageBusSubscriptions property "manually" in the base rowviewmodel classes. Some of these RowViewModels are definitely used outside the scope of the ElementDefinitionBrowser.

**Review by alexatrhea — APPROVED** [review]

**Review by alexatrhea — APPROVED** [review]

**Review by samatrhea — APPROVED** [review]
