### PR TITLE
[FIX] freeze upon closing a browser;fixes #1264

### LINKED ISSUE #1264: After filtering and sorting in the ED browser, the COMET-IME may crash
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [ x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Closing the element definitions browser still causes COMET to freeze and/or crash (this seems to be more likely to happen if I have applied some filtering & sorting in the browser or expanded some drop-down lists)

### Steps to Reproduce
open a model, naviage to the ED browser and apply filtering and sorting and expand various drop-down lists

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.5.0

### PR DESCRIPTION
**Pull request by lxatrhea**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-IME [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-IME-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
[FIX] freeze upon closing a browser;fixes #1264

### CODE REVIEW

File: CDP4Composition/Mvvm/ViewModelBase.cs [hunk 1]
```diff
@@ -315,7 +315,7 @@ protected virtual void Dispose(bool disposing)
             {
                 // Clear all property values that maybe have been set
                 // when the class was instantiated
-                this.RevisionNumber = 0;
+                this.revisionNumber = 0; //Don't set the reactive property this.RevisionNumber here. Otherwise NotifyChange might execute unwanted code.
```
Comment (alexatrhea) [inline CDP4Composition/Mvvm/ViewModelBase.cs:318]: @samatrhea any clue why we had to set this in the Dispose in any case?

**Review by alexatrhea — APPROVED** [review]

File: CDP4Composition/Mvvm/ViewModelBase.cs (hunk 1 above)
Comment (samatrhea) [reply CDP4Composition/Mvvm/ViewModelBase.cs:318]: no, no clear idea

**Review by samatrhea — APPROVED** [review]
